name: deploy-to-pantheon
inputs:
  pantheon_ssh_key:
    description: ' '
    required: true

  terminus_machine_token:
    description: ' '
    required: true

  pantheon_site:
    description: ' '
    required: true


  # Eventually the target_env argument will be needed by those
  # doing long-running integration multidevs. But for now
  # it is preferable to have as few required, or even available arguments
  # as possible.
  # target_env:
  #   description: ' '
  #   required: true

  # Eventually we'll need to test not-yet-merge changes in the
  # Build Tools Plugin. When that happens, we need a mechanism
  # to install specific versions of Build Tools.
  # build_tools_version:
  #   description: ' '
  #   required: false

runs:
    using: 'composite'
    steps:

      - uses: actions/checkout@v2

      - name: set target_env
        id: set_target_env
        shell: bash
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
        run: |
          #!/bin/bash
          set +e
          if [ -n "${PR_NUM}" ]; then
            TARGET_ENV="pr-${PR_NUM}"
          else
            TARGET_ENV='dev'
          fi

          echo "::set-output name=TARGET_ENV::$TARGET_ENV"



      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: ${{ steps.set_target_env.outputs.TARGET_ENV }}
          ref: ${{ github.head_ref }}

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ inputs.pantheon_ssh_key }}

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ inputs.terminus_machine_token }}

      - name: Deployment Processing
        shell: bash
        env:
          PANTHEON_SITE: ${{ inputs.pantheon_site }}
          TARGET_ENV: ${{ steps.set_target_env.outputs.TARGET_ENV }}
        run: |
          #!/bin/bash
          set +e

          git clone  -b <branch> git@github.com:stevector-streaming/terminus-build-tools-plugin.git

          terminus self:plugin:install "./terminus-build-tools-plugin"
          git fetch --unshallow origin
          git config --global user.email "GitHubAction@example.com"
          git config --global user.name "GitHub Action"
          terminus build:env:create $PANTHEON_SITE.live ${TARGET_ENV} --create-before-push

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          ref: ${{ github.head_ref }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.set_target_env.outputs.TARGET_ENV }}
          env_url: https://${{ steps.set_target_env.outputs.TARGET_ENV }}-${{ inputs.pantheon_site }}.pantheonsite.io
