name: Delete the Multidevs associated with closed pull requests
inputs:
  terminus_machine_token:
    description: ' '
    required: true

  pantheon_ssh_key:
    description: ' '
    required: true

  pantheon_site:
    description: ' '
    required: true

  relative_site_root:
    description: "The root directory of the site to be deployed relative to the repository root. The vast majority of users of this action should leave this value unchanged from the default. The action will use this value to change directories after checking out the repo."
    required: false
    default: ""

runs:
    using: 'composite'
    steps:

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ inputs.pantheon_ssh_key }}

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ inputs.terminus_machine_token }}

      - name: Install Terminus Plugin
        shell: bash
        run: |
          #!/bin/bash
          set +e
          terminus self:plugin:install "${{ github.action_path }}/../../terminus-build-tools-plugin"

      - name: Prepare site root
        shell: bash
        env:
          SITE_ROOT: ${{ inputs.relative_site_root }}
        run: |
          #!/bin/bash
          set +e
          if [ -n "$SITE_ROOT" ]; then
            cd ${SITE_ROOT}
                  git init
                  echo "this origin setting is a hack to get past the 'inferring' of a git provider in build tools"
                  git remote add origin https://github.com/${{ github.repository }}
          fi

      - name: Deleting old multidevs
        shell: bash
        env:
          PANTHEON_SITE: ${{ inputs.pantheon_site }}
          GITHUB_TOKEN: ${{ github.token }}
          SITE_ROOT: ${{ inputs.relative_site_root }}
        run: |
          #!/bin/bash
          set +e

          if [ -n "$SITE_ROOT" ]; then
            cd ${SITE_ROOT}
          fi

          terminus build:env:delete:pr $PANTHEON_SITE --yes

