name: Delete the Multidevs associated with closed pull requests
inputs:
  terminus_machine_token:
    description: ' '
    required: true

  pantheon_ssh_key:
    description: ' '
    required: true

  pantheon_site:
    description: ' '
    required: true

  # Eventually we'll need to test not-yet-merge changes in the
  # Build Tools Plugin. When that happens, we need a mechanism
  # to install specific versions of Build Tools.
  # build_tools_version:
  #   description: ' '
  #   required: false

runs:
    using: 'composite'
    steps:

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ inputs.pantheon_ssh_key }}

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ inputs.terminus_machine_token }}

      - name: Deployment Processing
        shell: bash
        env:
          PANTHEON_SITE: ${{ inputs.pantheon_site }}
          GITHUB_TOKEN: ${{ github.token }}

        run: |
          #!/bin/bash
          set +e
          terminus self:plugin:install terminus-build-tools-plugin
          terminus build:env:delete:pr $PANTHEON_SITE --yes

