name: deploy-to-pantheon
inputs:
  pantheon_ssh_key:
    description: ' '
    required: true

  terminus_machine_token:
    description: ' '
    required: true

  pantheon_site:
    description: ' '
    required: true

  # Eventually the target_env argument will be needed by those
  # doing long-running integration multidevs. But for now
  # it is preferable to have as few required, or even available arguments
  # as possible.
  # target_env:
  #   description: ' '
  #   required: true

  # Eventually we'll need to test not-yet-merge changes in the
  # Build Tools Plugin. When that happens, we need a mechanism
  # to install specific versions of Build Tools.
  # build_tools_version:
  #   description: ' '
  #   required: false

runs:
    using: 'composite'
    steps:

  
      - run: echo 'path=${{ github.action_path }}/..' >> $GITHUB_OUTPUT
        id: get-path
        shell: bash

      - name: set target_env
        id: set_target_env
        shell: bash
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
        run: |
          #!/bin/bash
          set +e
          ls
          pwd
          echo ${{ github.action_path }}
          ls ${{ github.action_path }}
          find ${{ github.action_path }}
          

          if [ -n "${PR_NUM}" ]; then
            TARGET_ENV="pr-${PR_NUM}"
          else
            TARGET_ENV='dev'
          fi

          echo "::set-output name=TARGET_ENV::$TARGET_ENV"


