name: deploy-to-pantheon
inputs:
  pantheon_ssh_key:
    description: ' '
    required: true

  terminus_machine_token:
    description: ' '
    required: true

  pantheon_site:
    description: ' '
    required: true

  target_env:
    description: ' '
    required: true

  relative_site_root:
    description: "The root directory of the site to be deployed relative to the repository root. The vast majority of users of this action should leave this value unchanged from the default. The action will use this value to change directories after checking out the repo."
    required: false
    default: ""

  git_user_name:
    description: "The name to be used with the Git commit that will be pushed to Pantheon. This value is not used on newer 'eVCS' sites for which there is no Pantheon-provided Git Repo"
    required: false
    default: "GitHub Action Automation"

  git_user_email:
    description: "The email address to be used with the Git commit that will be pushed to Pantheon. This value is not used on newer 'eVCS' sites for which there is no Pantheon-provided Git Repo"
    required: false
    default: "GitHubAction@example.com"

  git_commit_message:
    description: "A custom commit message to be used with the Git commit that will be pushed to Pantheon. Leaving this Action parameter blank will result in a generic commit message being used. This value is not used on newer 'eVCS' sites for which there is no Pantheon-provided Git Repo"
    required: false
    default: ""

  # todo checkout_repo:
  #   description: "A boolean for whether or not this composite step should checkout the git repo. Set to false if a checkout has already been perf"

runs:
    using: 'composite'
    steps:

      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ github.token }}
          env: ${{ inputs.target_env }}
          ref: ${{ github.head_ref }}

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ inputs.pantheon_ssh_key }}

      # todo, make checkout conditional.
      # Consumers might have checked out before calling this
      # composite action.
      # todo, switch to v4
      - uses: actions/checkout@v4

      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ inputs.terminus_machine_token }}

      - name: Install Terminus Plugin
        shell: bash
        run: |
          #!/bin/bash
          set +e
          terminus self:plugin:install "${{ github.action_path }}/../../terminus-build-tools-plugin"

      - name: Configure Git User
        shell: bash
        env:
          PANTHEON_GIT_USER_NAME: ${{ inputs.git_user_name }}
          PANTHEON_GIT_USER_EMAIL: ${{ inputs.git_user_email }}
        run: |
          #!/bin/bash
          set +e
          git config --global user.email "${PANTHEON_GIT_USER_EMAIL}"
          git config --global user.name "${PANTHEON_GIT_USER_NAME}"

      - name: Prepare site root
        shell: bash
        env:
          SITE_ROOT: ${{ inputs.relative_site_root }}
        run: |
          #!/bin/bash
          set +e
          if [ -n "$SITE_ROOT" ]; then
            cd ${SITE_ROOT}
            git init
            echo "this origin setting is a hack to get past the 'inferring' of a git provider in build tools"
            git remote add origin https://github.com
          else
            git fetch --unshallow origin
          fi

      - name: Deployment Processing
        shell: bash
        env:
          PANTHEON_SITE: ${{ inputs.pantheon_site }}
          TARGET_ENV: ${{ inputs.target_env }}
          SITE_ROOT: ${{ inputs.relative_site_root }}
          PANTHEON_COMMIT_MESSAGE: ${{ inputs.git_commit_message }}
          # todo, might need to make this configurable too.
          # the default in build tools is 180. But that's regularly failing
          # on a small personal site.
          TERMINUS_BUILD_TOOLS_WORKFLOW_TIMEOUT: 300
        run: |
          #!/bin/bash
          set +e

          if [ -n "$SITE_ROOT" ]; then
            cd ${SITE_ROOT}
          fi

          terminus -n build:env:create ${PANTHEON_SITE}.live ${TARGET_ENV} --yes  --message="${PANTHEON_COMMIT_MESSAGE}"

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ github.token }}
          status: ${{ job.status }}
          ref: ${{ github.head_ref }}
          # todo, how does this work when there is a step above with the id of "deployment" not "deployment_id"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ inputs.target_env }}-${{ inputs.pantheon_site }}
          env_url: https://${{ inputs.target_env }}-${{ inputs.pantheon_site }}.pantheonsite.io
