name: Deploy PR to Pantheon

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: false

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: deploy to Pantheon
      uses: ./github_actions/deploy_single_site
      with:
        pantheon_ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        terminus_machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        pantheon_site: dtp-nearly-empty-site
        target_env: "pr-${{ github.event.pull_request.number }}"
        relative_site_root: ".github/testing_fixtures/dtp-nearly-empty-site"
        git_user_name: "Test Name"
        git_user_email: "test@example.com"
        git_commit_message: "This is an automated commit message from GitHub Actions."

  cleanup_multidevs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Delete old multidevs
      uses: ./github_actions/delete-closed-pull-request-multidevs
      with:
        pantheon_ssh_key: ${{ secrets.PANTHEON_SSH_KEY }}
        terminus_machine_token: ${{ secrets.TERMINUS_MACHINE_TOKEN }}
        pantheon_site: dtp-nearly-empty-site
